/usr/share/nmap/scripts]
└─$ ls
acarsd-info.nse                       dns-random-srcport.nse              http-hp-ilo-info.nse                    ip-geolocation-ipinfodb.nse    nrpe-enum.nse                   smb-webexec-exploit.nse
address-info.nse                      dns-random-txid.nse                 http-huawei-hg5xx-vuln.nse              ip-geolocation-map-bing.nse    ntp-info.nse                    smtp-brute.nse
afp-brute.nse                         dns-recursion.nse                   http-icloud-findmyiphone.nse            ip-geolocation-map-google.nse  ntp-monlist.nse                 smtp-commands.nse
afp-ls.nse                            dns-service-discovery.nse           http-icloud-sendmsg.nse                 ip-geolocation-map-kml.nse     omp2-brute.nse                  smtp-enum-users.nse
afp-path-vuln.nse                     dns-srv-enum.nse                    http-iis-short-name-brute.nse           ip-geolocation-maxmind.nse     omp2-enum-targets.nse           smtp-ntlm-info.nse
afp-serverinfo.nse                    dns-update.nse                      http-iis-webdav-vuln.nse                ip-https-discover.nse          omron-info.nse                  smtp-open-relay.nse
afp-showmount.nse                     dns-zeustracker.nse                 http-internal-ip-disclosure.nse         ipidseq.nse                    openflow-info.nse               smtp-strangeport.nse
ajp-auth.nse                          dns-zone-transfer.nse               http-joomla-brute.nse                   ipmi-brute.nse                 openlookup-info.nse             smtp-vuln-cve2010-4344.nse
ajp-brute.nse                         docker-version.nse                  http-jsonp-detection.nse                ipmi-cipher-zero.nse           openvas-otp-brute.nse           smtp-vuln-cve2011-1720.nse
ajp-headers.nse                       domcon-brute.nse                    http-litespeed-sourcecode-download.nse  ipmi-version.nse               openwebnet-discovery.nse        smtp-vuln-cve2011-1764.nse
ajp-methods.nse                       domcon-cmd.nse                      http-ls.nse                             ipv6-multicast-mld-list.nse    oracle-brute.nse                sniffer-detect.nse
ajp-request.nse                       domino-enum-users.nse               http-majordomo2-dir-traversal.nse       ipv6-node-info.nse             oracle-brute-stealth.nse        snmp-brute.nse
allseeingeye-info.nse                 dpap-brute.nse                      http-malware-host.nse                   ipv6-ra-flood.nse              oracle-enum-users.nse           snmp-hh3c-logins.nse
amqp-info.nse                         drda-brute.nse                      http-mcmp.nse                           irc-botnet-channels.nse        oracle-sid-brute.nse            snmp-info.nse
asn-query.nse                         drda-info.nse                       http-methods.nse                        irc-brute.nse                  oracle-tns-version.nse          snmp-interfaces.nse
auth-owners.nse                       duplicates.nse                      http-method-tamper.nse                  irc-info.nse                   ovs-agent-version.nse           snmp-ios-config.nse
auth-spoof.nse                        eap-info.nse                        http-mobileversion-checker.nse          irc-sasl-brute.nse             p2p-conficker.nse               snmp-netstat.nse
backorifice-brute.nse                 enip-info.nse                       http-ntlm-info.nse                      irc-unrealircd-backdoor.nse    path-mtu.nse                    snmp-processes.nse
backorifice-info.nse                  epmd-info.nse                       http-open-proxy.nse                     iscsi-brute.nse                pcanywhere-brute.nse            snmp-sysdescr.nse
bacnet-info.nse                       eppc-enum-processes.nse             http-open-redirect.nse                  iscsi-info.nse                 pcworx-info.nse                 snmp-win32-services.nse
banner.nse                            fcrdns.nse                          http-passwd.nse                         isns-info.nse                  pgsql-brute.nse                 snmp-win32-shares.nse
bitcoin-getaddr.nse                   finger.nse                          http-phpmyadmin-dir-traversal.nse       jdwp-exec.nse                  pjl-ready-message.nse           snmp-win32-software.nse
bitcoin-info.nse                      fingerprint-strings.nse             http-phpself-xss.nse                    jdwp-info.nse                  pop3-brute.nse                  snmp-win32-users.nse
bitcoinrpc-info.nse                   firewalk.nse                        http-php-version.nse                    jdwp-inject.nse                pop3-capabilities.nse           socks-auth-info.nse
bittorrent-discovery.nse              firewall-bypass.nse                 http-proxy-brute.nse                    jdwp-version.nse               pop3-ntlm-info.nse              socks-brute.nse
bjnp-discover.nse                     flume-master-info.nse               http-put.nse                            knx-gateway-discover.nse       port-states.nse                 socks-open-proxy.nse
broadcast-ataoe-discover.nse          fox-info.nse                        http-qnap-nas-info.nse                  knx-gateway-info.nse           pptp-version.nse                ssh2-enum-algos.nse
broadcast-avahi-dos.nse               freelancer-info.nse                 http-referer-checker.nse                krb5-enum-users.nse            puppet-naivesigning.nse         ssh-auth-methods.nse
broadcast-bjnp-discover.nse           ftp-anon.nse                        http-rfi-spider.nse                     ldap-brute.nse                 qconn-exec.nse                  ssh-brute.nse
broadcast-db2-discover.nse            ftp-bounce.nse                      http-robots.txt.nse                     ldap-novell-getpass.nse        qscan.nse                       ssh-hostkey.nse
broadcast-dhcp6-discover.nse          ftp-brute.nse                       http-robtex-reverse-ip.nse              ldap-rootdse.nse               quake1-info.nse                 ssh-publickey-acceptance.nse
broadcast-dhcp-discover.nse           ftp-libopie.nse                     http-robtex-shared-ns.nse               ldap-search.nse                quake3-info.nse                 ssh-run.nse
broadcast-dns-service-discovery.nse   ftp-proftpd-backdoor.nse            http-sap-netweaver-leak.nse             lexmark-config.nse             quake3-master-getservers.nse    sshv1.nse
broadcast-dropbox-listener.nse        ftp-syst.nse                        http-security-headers.nse               llmnr-resolve.nse              rdp-enum-encryption.nse         ssl-ccs-injection.nse
broadcast-eigrp-discovery.nse         ftp-vsftpd-backdoor.nse             http-server-header.nse                  lltd-discovery.nse             rdp-ntlm-info.nse               ssl-cert-intaddr.nse
broadcast-hid-discoveryd.nse          ftp-vuln-cve2010-4221.nse           http-shellshock.nse                     lu-enum.nse                    rdp-vuln-ms12-020.nse           ssl-cert.nse
broadcast-igmp-discovery.nse          ganglia-info.nse                    http-sitemap-generator.nse              maxdb-info.nse                 realvnc-auth-bypass.nse         ssl-date.nse
broadcast-jenkins-discover.nse        giop-info.nse                       http-slowloris-check.nse                mcafee-epo-agent.nse           redis-brute.nse                 ssl-dh-params.nse
broadcast-listener.nse                gkrellm-info.nse                    http-slowloris.nse                      membase-brute.nse              redis-info.nse                  ssl-enum-ciphers.nse
broadcast-ms-sql-discover.nse         gopher-ls.nse                       http-sql-injection.nse                  membase-http-info.nse          resolveall.nse                  ssl-heartbleed.nse
broadcast-netbios-master-browser.nse  gpsd-info.nse                       https-redirect.nse                      memcached-info.nse             reverse-index.nse               ssl-known-key.nse
broadcast-networker-discover.nse      hadoop-datanode-info.nse            http-stored-xss.nse                     metasploit-info.nse            rexec-brute.nse                 ssl-poodle.nse
broadcast-novell-locate.nse           hadoop-jobtracker-info.nse          http-svn-enum.nse                       metasploit-msgrpc-brute.nse    rfc868-time.nse                 sslv2-drown.nse
broadcast-ospf2-discover.nse          hadoop-namenode-info.nse            http-svn-info.nse                       metasploit-xmlrpc-brute.nse    riak-http-info.nse              sslv2.nse
broadcast-pc-anywhere.nse             hadoop-secondary-namenode-info.nse  http-title.nse                          mikrotik-routeros-brute.nse    rlogin-brute.nse                sstp-discover.nse
broadcast-pc-duo.nse                  hadoop-tasktracker-info.nse         http-tplink-dir-traversal.nse           mmouse-brute.nse               rmi-dumpregistry.nse            stun-info.nse
broadcast-pim-discovery.nse           hbase-master-info.nse               http-trace.nse                          mmouse-exec.nse                rmi-vuln-classloader.nse        stun-version.nse
broadcast-ping.nse                    hbase-region-info.nse               http-traceroute.nse                     modbus-discover.nse            rpcap-brute.nse                 stuxnet-detect.nse
broadcast-pppoe-discover.nse          hddtemp-info.nse                    http-trane-info.nse                     mongodb-brute.nse              rpcap-info.nse                  supermicro-ipmi-conf.nse
broadcast-rip-discover.nse            hnap-info.nse                       http-unsafe-output-escaping.nse         mongodb-databases.nse          rpc-grind.nse                   svn-brute.nse
broadcast-ripng-discover.nse          hostmap-bfk.nse                     http-useragent-tester.nse               mongodb-info.nse               rpcinfo.nse                     targets-asn.nse
broadcast-sonicwall-discover.nse      hostmap-crtsh.nse                   http-userdir-enum.nse                   mqtt-subscribe.nse             rsa-vuln-roca.nse               targets-ipv6-map4to6.nse
broadcast-sybase-asa-discover.nse     hostmap-robtex.nse                  http-vhosts.nse                         mrinfo.nse                     rsync-brute.nse                 targets-ipv6-multicast-echo.nse
broadcast-tellstick-discover.nse      http-adobe-coldfusion-apsa1301.nse  http-virustotal.nse                     msrpc-enum.nse                 rsync-list-modules.nse          targets-ipv6-multicast-invalid-dst.nse
broadcast-upnp-info.nse               http-affiliate-id.nse               http-vlcstreamer-ls.nse                 ms-sql-brute.nse               rtsp-methods.nse                targets-ipv6-multicast-mld.nse
broadcast-versant-locate.nse          http-apache-negotiation.nse         http-vmware-path-vuln.nse               ms-sql-config.nse              rtsp-url-brute.nse              targets-ipv6-multicast-slaac.nse
broadcast-wake-on-lan.nse             http-apache-server-status.nse       http-vuln-cve2006-3392.nse              ms-sql-dac.nse                 rusers.nse                      targets-ipv6-wordlist.nse
broadcast-wpad-discover.nse           http-aspnet-debug.nse               http-vuln-cve2009-3960.nse              ms-sql-dump-hashes.nse         s7-info.nse                     targets-sniffer.nse
broadcast-wsdd-discover.nse           http-auth-finder.nse                http-vuln-cve2010-0738.nse              ms-sql-empty-password.nse      samba-vuln-cve-2012-1182.nse    targets-traceroute.nse
broadcast-xdmcp-discover.nse          http-auth.nse                       http-vuln-cve2010-2861.nse              ms-sql-hasdbaccess.nse         script.db                       targets-xml.nse
cassandra-brute.nse                   http-avaya-ipoffice-users.nse       http-vuln-cve2011-3192.nse              ms-sql-info.nse                servicetags.nse                 teamspeak2-version.nse
cassandra-info.nse                    http-awstatstotals-exec.nse         http-vuln-cve2011-3368.nse              ms-sql-ntlm-info.nse           shodan-api.nse                  telnet-brute.nse
cccam-version.nse                     http-axis2-dir-traversal.nse        http-vuln-cve2012-1823.nse              ms-sql-query.nse               sip-brute.nse                   telnet-encryption.nse
cics-enum.nse                         http-backup-finder.nse              http-vuln-cve2013-0156.nse              ms-sql-tables.nse              sip-call-spoof.nse              telnet-ntlm-info.nse
cics-info.nse                         http-barracuda-dir-traversal.nse    http-vuln-cve2013-6786.nse              ms-sql-xp-cmdshell.nse         sip-enum-users.nse              tftp-enum.nse
cics-user-brute.nse                   http-bigip-cookie.nse               http-vuln-cve2013-7091.nse              mtrace.nse                     sip-methods.nse                 tftp-version.nse
cics-user-enum.nse                    http-brute.nse                      http-vuln-cve2014-2126.nse              murmur-version.nse             skypev2-version.nse             tls-alpn.nse
citrix-brute-xml.nse                  http-cakephp-version.nse            http-vuln-cve2014-2127.nse              mysql-audit.nse                smb2-capabilities.nse           tls-nextprotoneg.nse
citrix-enum-apps.nse                  http-chrono.nse                     http-vuln-cve2014-2128.nse              mysql-brute.nse                smb2-security-mode.nse          tls-ticketbleed.nse
citrix-enum-apps-xml.nse              http-cisco-anyconnect.nse           http-vuln-cve2014-2129.nse              mysql-databases.nse            smb2-time.nse                   tn3270-screen.nse
citrix-enum-servers.nse               http-coldfusion-subzero.nse         http-vuln-cve2014-3704.nse              mysql-dump-hashes.nse          smb2-vuln-uptime.nse            tor-consensus-checker.nse
citrix-enum-servers-xml.nse           http-comments-displayer.nse         http-vuln-cve2014-8877.nse              mysql-empty-password.nse       smb-brute.nse                   traceroute-geolocation.nse
clamav-exec.nse                       http-config-backup.nse              http-vuln-cve2015-1427.nse              mysql-enum.nse                 smb-double-pulsar-backdoor.nse  tso-brute.nse
clock-skew.nse                        http-cookie-flags.nse               http-vuln-cve2015-1635.nse              mysql-info.nse                 smb-enum-domains.nse            tso-enum.nse
coap-resources.nse                    http-cors.nse                       http-vuln-cve2017-1001000.nse           mysql-query.nse                smb-enum-groups.nse             ubiquiti-discovery.nse
couchdb-databases.nse                 http-cross-domain-policy.nse        http-vuln-cve2017-5638.nse              mysql-users.nse                smb-enum-processes.nse          unittest.nse
couchdb-stats.nse                     http-csrf.nse                       http-vuln-cve2017-5689.nse              mysql-variables.nse            smb-enum-services.nse           unusual-port.nse
creds-summary.nse                     http-date.nse                       http-vuln-cve2017-8917.nse              mysql-vuln-cve2012-2122.nse    smb-enum-sessions.nse           upnp-info.nse
cups-info.nse                         http-default-accounts.nse           http-vuln-misfortune-cookie.nse         nat-pmp-info.nse               smb-enum-shares.nse             uptime-agent-info.nse
cups-queue-info.nse                   http-devframework.nse               http-vuln-wnr1000-creds.nse             nat-pmp-mapport.nse            smb-enum-users.nse              url-snarf.nse
cvs-brute.nse                         http-dlink-backdoor.nse             http-waf-detect.nse                     nbd-info.nse                   smb-flood.nse                   ventrilo-info.nse
cvs-brute-repository.nse              http-dombased-xss.nse               http-waf-fingerprint.nse                nbns-interfaces.nse            smb-ls.nse                      versant-info.nse
daap-get-library.nse                  http-domino-enum-passwords.nse      http-webdav-scan.nse                    nbstat.nse                     smb-mbenum.nse                  vmauthd-brute.nse
daytime.nse                           http-drupal-enum.nse                http-wordpress-brute.nse                ncp-enum-users.nse             smb-os-discovery.nse            vmware-version.nse
db2-das-info.nse                      http-drupal-enum-users.nse          http-wordpress-enum.nse                 ncp-serverinfo.nse             smb-print-text.nse              vnc-brute.nse
deluge-rpc-brute.nse                  http-enum.nse                       http-wordpress-users.nse                ndmp-fs-info.nse               smb-protocols.nse               vnc-info.nse
dhcp-discover.nse                     http-errors.nse                     http-xssed.nse                          ndmp-version.nse               smb-psexec.nse                  vnc-title.nse
dicom-brute.nse                       http-exif-spider.nse                iax2-brute.nse                          nessus-brute.nse               smb-security-mode.nse           voldemort-info.nse
dicom-ping.nse                        http-favicon.nse                    iax2-version.nse                        nessus-xmlrpc-brute.nse        smb-server-stats.nse            vtam-enum.nse
dict-info.nse                         http-feed.nse                       icap-info.nse                           netbus-auth-bypass.nse         smb-system-info.nse             vulners.nse
distcc-cve2004-2687.nse               http-fetch.nse                      iec-identify.nse                        netbus-brute.nse               smb-vuln-conficker.nse          vuze-dht-info.nse
dns-blacklist.nse                     http-fileupload-exploiter.nse       ike-version.nse                         netbus-info.nse                smb-vuln-cve2009-3103.nse       wdb-version.nse
dns-brute.nse                         http-form-brute.nse                 imap-brute.nse                          netbus-version.nse             smb-vuln-cve-2017-7494.nse      weblogic-t3-info.nse
dns-cache-snoop.nse                   http-form-fuzzer.nse                imap-capabilities.nse                   nexpose-brute.nse              smb-vuln-ms06-025.nse           whois-domain.nse
dns-check-zone.nse                    http-frontpage-login.nse            imap-ntlm-info.nse                      nfs-ls.nse                     smb-vuln-ms07-029.nse           whois-ip.nse
dns-client-subnet-scan.nse            http-generator.nse                  impress-remote-discover.nse             nfs-showmount.nse              smb-vuln-ms08-067.nse           wsdd-discover.nse
dns-fuzz.nse                          http-git.nse                        informix-brute.nse                      nfs-statfs.nse                 smb-vuln-ms10-054.nse           x11-access.nse
dns-ip6-arpa-scan.nse                 http-gitweb-projects-enum.nse       informix-query.nse                      nje-node-brute.nse             smb-vuln-ms10-061.nse           xdmcp-discover.nse
dns-nsec3-enum.nse                    http-google-malware.nse             informix-tables.nse                     nje-pass-brute.nse             smb-vuln-ms17-010.nse           xmlrpc-methods.nse
dns-nsec-enum.nse                     http-grep.nse                       ip-forwarding.nse                       nntp-ntlm-info.nse             smb-vuln-regsvc-dos.nse         xmpp-brute.nse
dns-nsid.nse                          http-headers.nse                    ip-geolocation-geoplugin.nse            nping-brute.nse                smb-vuln-webexec.nse            xmpp-info.nse
